name: ivp_vae
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py310h5764c6d_1
  - aiohttp-cors=0.7.0=py_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - autopep8=1.6.0=pyhd3eb1b0_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blessed=1.19.1=pyhe4f9e05_2
  - blinker=1.5=pyhd8ed1ab_0
  - blosc=1.21.3=h6a678d5_0
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310hff52083_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorful=0.5.4=pyhd8ed1ab_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cryptography=38.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - distlib=0.3.6=pyhd8ed1ab_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.9=h27cfd23_1
  - filelock=3.10.0=pyhd8ed1ab_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py310h5eee18b_0
  - fsspec=2022.11.0=pyhd8ed1ab_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-api-core=2.8.1=pyhd8ed1ab_0
  - google-auth=2.15.0=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - googleapis-common-protos=1.57.0=py310hff52083_0
  - gpustat=1.0.0=pyhd8ed1ab_0
  - grpcio=1.42.0=py310hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=5.2.0=pyha770c72_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.2=py310h06a4308_0
  - ipython=8.7.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.1.1=py310h06a4308_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.8=py310h06a4308_0
  - jupyter_core=4.11.2=py310h06a4308_0
  - kiwisolver=1.4.2=py310h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libunwind=1.6.2=h9c3ff4c_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lightning-utilities=0.4.2=pyhd8ed1ab_0
  - lz4-c=1.9.4=h6a678d5_0
  - lzo=2.10=h7b6447c_2
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib=3.6.2=py310h06a4308_0
  - matplotlib-base=3.6.2=py310h945d387_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mock=4.0.3=pyhd3eb1b0_0
  - msgpack-python=1.0.3=py310hd09550d_0
  - multidict=6.0.2=py310h5764c6d_1
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.4=py310h8879344_0
  - numpy=1.23.5=py310hd5efca6_0
  - numpy-base=1.23.5=py310h8e6c178_0
  - nvidia-ml-py=11.495.46=pyhd8ed1ab_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - opencensus=0.11.2=pyhd8ed1ab_0
  - opencensus-context=0.1.3=py310hff52083_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.5.2=py310h1128e8f_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py310hace64e9_0
  - pip=22.3.1=py310h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.20.1=py310h295c915_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-spy=0.3.14=h52d8a92_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=0.18.2=py_0
  - pyg=2.2.0=py310_torch_1.12.0_cu113
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=py310h06a4308_0
  - pytables=3.7.0=py310hf19a122_1
  - python=3.10.8=h7a1cb2a_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8.3.2_0
  - pytorch-cluster=1.6.0=py310_torch_1.12.0_cu113
  - pytorch-lightning=1.8.1=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.0=py310_torch_1.12.0_cu113
  - pytorch-sparse=0.6.15=py310_torch_1.12.0_cu113
  - pytz=2022.1=py310h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=23.2.0=py310h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - ray-core=2.3.0=py310h6a678d5_0
  - ray-default=2.3.0=py310h06a4308_0
  - ray-tune=2.3.0=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.1.3=py310h6a678d5_0
  - scipy=1.9.3=py310hd5efca6_0
  - seaborn=0.12.2=py310h06a4308_0
  - setproctitle=1.2.2=py310h5764c6d_2
  - setuptools=65.5.0=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=6.3.0=pyhd8ed1ab_1
  - sqlite=3.40.0=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tensorboard=2.11.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorboardx=2.5.1=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py310_cu113
  - torchmetrics=0.11.0=pyhd8ed1ab_0
  - torchvision=0.13.1=py310_cu113
  - tornado=6.2=py310h5eee18b_0
  - tqdm=4.64.1=py310h06a4308_0
  - traitlets=5.7.1=py310h06a4308_0
  - typing-extensions=4.4.0=py310h06a4308_0
  - typing_extensions=4.4.0=py310h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.13=py310h06a4308_0
  - virtualenv=20.21.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py310h5764c6d_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - appdirs==1.4.4
    - beautifulsoup4==4.11.2
    - bs4==0.0.1
    - docker-pycreds==0.4.0
    - geotorch==0.3.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - icd10-cm==0.0.4
    - icd9cms==0.2.1
    - ipdb==0.13.11
    - llvmlite==0.39.1
    - numba==0.56.4
    - pathtools==0.1.2
    - pycorruptor==0.0.4
    - pyqt5-sip==12.11.0
    - sentry-sdk==1.17.0
    - smmap==5.0.0
    - soupsieve==2.4
    - sparse==0.13.0
    - tomli==2.0.1
    - torchdiffeq==0.2.3
    - tsdb==0.0.7
    - wandb==0.14.0
